name: sharkfin
description: just my personal bluefin.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/zeno/scrcpy/repo/fedora-%OS_VERSION%/zeno-scrcpy-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/matte-schwartz/sunshine/repo/fedora-%OS_VERSION%/matte-schwartz-sunshine-fedora-%OS_VERSION%.repo
    install:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
  - tyoe: rpm-ostree
    install:
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted
  - type: script
    snippet:
      - "rpm-ostree install *-firmware"
      - "git clone https://github.com/fabiscafe/game-devices-udev.git /var/tmp/game-devices-udev"
      - "git clone https://github.com/wget/realtek-r8152-linux.git /var/tmp/realtek-r8152-udev"
      - "cp -rfv /var/tmp/game-devices-udev/*.rules /usr/share/ublue-os/udev-rules/etc/udev/rules.d"
      - "cp -rfv /var/tmp/realtek-r8152-udev/*.rules /usr/share/ublue-os/udev-rules/etc/udev/rules.d"
      - "rm -rfv /var/tmp/game-devices-udev /var/tmp/realtek-r8152-udev"
  - type: rpm-ostree
    replace:
      - steam
    remove:
      - gnome-shell-extension-search-light
      - gnome-shell-extension-logo-menu
      - gnome-classic-session
      - gnome-classic-session-xsession
      - yaru-theme
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-ce-rootless-extras
      - devpod
    install:
      - gnome-shell-extension-caffeine
      - podman-docker
      - podman-compose
      - duperemove
      - corectrl
      - qt5-qtbase
      - qt6ct
      - mangohud
      - gamescope
      - gamemode
      - sunshine
      - libvirt-client
      - qemu-kvm
      - libvirt-daemon-kvm
      - libvirt-daemon-config-network
      - virt-install
      - virt-manager
      - edk2-ovmf
      - swtpm
      - virt-top
      - libguestfs-tools
      - tuned
      - bridge-utils
      - android-tools
      - scrcpy
      - waydroid
      - libdvdcss
      - gstreamer1-plugin-libav
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - gstreamer1-vaapi
      - ffmpeg
      - openrgb-udev-rules
      - steam-devices
      - solaar-udev
  - type: default-flatpaks
    notify: true 
    system:
    repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
    repo-name: flathub
    repo-title: "Flathub (System)"
    install:
      - org.mozilla.firefox
      - org.libreoffice.libreoffice
      - org.localsend.localsend_app
      - org.gnome.Geary
      - dev.geopjr.Collision
      - org.gnome.World.Secrets
      - com.belmoussaoui.Authenticator
      - com.vysp3r.ProtonPlus
      - com.usebottles.bottles
      - com.github.tchx84.Flatseal
      - io.github.Foldex.AdwSteamGtk
      - dev.qwery.AddWater
  - type: systemd
    system:
      enabled:
        - libvirtd.service
        - libvirtd.socket
        - podman.socket
    user:
      enabled:
        - podman.socket
  - type: justfiles
    validate: true
    include:
      - 95-sharkfin-waydroid.just
  - type: gnome-extensions
    install:
      - 4655
      - 6784
      - 3733
      - 5547
  - type: gschema-overrides
    include:
      - gnome_settings.gschema.override
  - type: script
    snippet:
      - "sed -i 's@bluefin-dx@sharkfin@g' /usr/share/ublue-os/image-info.json"
      - "sed -i 's@ublue-os@vibrantleaf@g' /usr/share/ublue-os/image-info.json"
      - "sed -i 's@ghcr.io/ublue-os/bluefin-dx@ghcr.io/vibrantlef/sharkfin@g' /usr/share/ublue-os/image-info.json"
  - type: signing
